CREATE TABLE INGREDIENTS(
 IID NUMBER(6) PRIMARY KEY,
 RID NUMBER(6) NOT NULL,
 QTY DOUBLE,
 AMOUNT DOUBLE,
 CONTAINR VARCHAR(100), 
 MEASUREMENT VARCHAR(100), 
 ITEM VARCHAR(250), 
 FOODGROUP VARCHAR(50),
 LST_UPDT DATE, 
 FOREIGN KEY (RID) REFERENCES RECIPES(RID)
);

COMMIT;