CREATE TABLE MENUS(
 MID NUMBER(6) NOT NULL,
 TITLE VARCHAR(100) NOT NULL,
CONSTRAINT MENU_PK PRIMARY KEY(MID)
);
COMMIT;

CREATE TABLE MENUITEMS (
 MIID NUMBER(6) NOT NULL,
 MID NUMBER(6) NOT NULL,
 RID NUMBER(6) NOT NULL,
 CONSTRAINT MENUITEM_PK PRIMARY KEY(MIID)
);
COMMIT;



