CREATE TABLE AISLES (
 FGID NUMBER(6) NOT NULL,
 FOODGROUP VARCHAR(150) NOT NULL,
 CONSTRAINT AISLE_PK PRIMARY KEY(FGID)
);
COMMIT;

CREATE TABLE FOODITEMS (
 FID NUMBER(6) NOT NULL,
 FGID NUMBER(6) NOT NULL,
 ITEM VARCHAR(250) NOT NULL
);
COMMIT;

